package smart.budget.application;
// Generated 06 Jun 2019 12:58:24 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Account generated by hbm2java
 */
@Entity
@Table(name="account"
    ,catalog="smart_budget_data_model"
    , uniqueConstraints = {@UniqueConstraint(columnNames="email"), @UniqueConstraint(columnNames="phone")} 
)
public class Account  implements java.io.Serializable {


     private Integer idaccount;
     private Budget budget;
     private SmartTransaction smarttransaction;
     private User user;
     private Wallet wallet;
     private String accName;
     private String accSurname;
     private String email;
     private String phone;
     private String country;
     private String state;
     private String city;
     private String zip;

    public Account() {
    }

	
    public Account(Budget budget, SmartTransaction smarttransaction, User user, Wallet wallet, String accName, String accSurname, String email, String phone) {
        this.budget = budget;
        this.smarttransaction = smarttransaction;
        this.user = user;
        this.wallet = wallet;
        this.accName = accName;
        this.accSurname = accSurname;
        this.email = email;
        this.phone = phone;
    }
    public Account(Budget budget, SmartTransaction smarttransaction, User user, Wallet wallet, String accName, String accSurname, String email, String phone, String country, String state, String city, String zip) {
       this.budget = budget;
       this.smarttransaction = smarttransaction;
       this.user = user;
       this.wallet = wallet;
       this.accName = accName;
       this.accSurname = accSurname;
       this.email = email;
       this.phone = phone;
       this.country = country;
       this.state = state;
       this.city = city;
       this.zip = zip;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idaccount", unique=true, nullable=false)
    public Integer getIdaccount() {
        return this.idaccount;
    }
    
    public void setIdaccount(Integer idaccount) {
        this.idaccount = idaccount;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idBudget", nullable=false)
    public Budget getBudget() {
        return this.budget;
    }
    
    public void setBudget(Budget budget) {
        this.budget = budget;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idTransaction", nullable=false)
    public SmartTransaction getSmarttransaction() {
        return this.smarttransaction;
    }
    
    public void setSmarttransaction(SmartTransaction smarttransaction) {
        this.smarttransaction = smarttransaction;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="iduser", nullable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idwallet", nullable=false)
    public Wallet getWallet() {
        return this.wallet;
    }
    
    public void setWallet(Wallet wallet) {
        this.wallet = wallet;
    }

    
    @Column(name="accName", nullable=false, length=45)
    public String getAccName() {
        return this.accName;
    }
    
    public void setAccName(String accName) {
        this.accName = accName;
    }

    
    @Column(name="accSurname", nullable=false, length=45)
    public String getAccSurname() {
        return this.accSurname;
    }
    
    public void setAccSurname(String accSurname) {
        this.accSurname = accSurname;
    }

    
    @Column(name="email", unique=true, nullable=false, length=45)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="phone", unique=true, nullable=false, length=45)
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }

    
    @Column(name="country", length=45)
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }

    
    @Column(name="state", length=45)
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }

    
    @Column(name="city", length=45)
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }

    
    @Column(name="zip", length=45)
    public String getZip() {
        return this.zip;
    }
    
    public void setZip(String zip) {
        this.zip = zip;
    }




}


