package smart.budget.application;
// Generated 06 Jun 2019 12:58:24 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Scanner;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Budget generated by hbm2java
 */
@Entity
@Table(name="budget"
    ,catalog="smart_budget_data_model"
)
public class Budget  implements java.io.Serializable {


     private Integer idBudget;
     private String budgName;
     private double budgAmnt;
     private String budgCat;
     private String budgDate;
     private Set<Account> accounts = new HashSet<Account>(0);

    public Budget() {
    }

	
    public Budget(String budgName, double budgAmnt, String budgCat, String budgDate) {
        this.budgName = budgName;
        this.budgAmnt = budgAmnt;
        this.budgCat = budgCat;
        this.budgDate = budgDate;
    }
    public Budget(String budgName, double budgAmnt, String budgCat, String budgDate, Set<Account> accounts) {
       this.budgName = budgName;
       this.budgAmnt = budgAmnt;
       this.budgCat = budgCat;
       this.budgDate = budgDate;
       this.accounts = accounts;
    }
    
    /*public void getBudgetData(){
    
        Scanner keyboard = new Scanner(System.in);
        System.out.println("Enter budget name");
        budgName = keyboard.next();
        System.out.println("Enter budget Amount");
        budgAmnt = keyboard.nextDouble();
        System.out.println("Enter budhet Cartegory");
        keyboard.next();
    }*/
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idBudget", unique=true, nullable=false)
    public Integer getIdBudget() {
        return this.idBudget;
    }
    
    public void setIdBudget(Integer idBudget) {
        this.idBudget = idBudget;
    }

    
    @Column(name="budgName", nullable=false, length=45)
    public String getBudgName() {
        return this.budgName;
    }
    
    public void setBudgName(String budgName) {
        this.budgName = budgName;
    }

    
    @Column(name="budgAmnt", nullable=false, precision=22, scale=0)
    public double getBudgAmnt() {
        return this.budgAmnt;
    }
    
    public void setBudgAmnt(double budgAmnt) {
        this.budgAmnt = budgAmnt;
    }

    
    @Column(name="budgCat", nullable=false, length=45)
    public String getBudgCat() {
        return this.budgCat;
    }
    
    public void setBudgCat(String budgCat) {
        this.budgCat = budgCat;
    }

    
    @Column(name="budgDate", nullable=false, length=45)
    public String getBudgDate() {
        return this.budgDate;
    }
    
    public void setBudgDate(String budgDate) {
        this.budgDate = budgDate;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="budget")
    public Set<Account> getAccounts() {
        return this.accounts;
    }
    
    public void setAccounts(Set<Account> accounts) {
        this.accounts = accounts;
    }




}


