package smart.budget.application;
// Generated 06 Jun 2019 12:58:24 PM by Hibernate Tools 4.3.1


import java.util.Scanner;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SmartTransaction generated by hbm2java
 */
@Entity
@Table(name="smarttransaction"
    ,catalog="smart_budget_data_model"
)
public class SmartTransaction  implements java.io.Serializable {


     private Integer idTransaction;
     private String transName;
     private double transAmount;
     private String transDate;
     private String transCart;
     private Set<Account> accounts = new HashSet<Account>(0);

    public SmartTransaction() {
    }

	
    public SmartTransaction(String transName, double transAmount, String transDate) {
        this.transName = transName;
        this.transAmount = transAmount;
        this.transDate = transDate;
    }
    public SmartTransaction(String transName, double transAmount, String transDate, String transCart, Set<Account> accounts) {
       this.transName = transName;
       this.transAmount = transAmount;
       this.transDate = transDate;
       this.transCart = transCart;
       this.accounts = accounts;
    }
   
    public void getTransactionData(){
    
        Scanner keyboard = new Scanner(System.in);
        
        System.out.println("Enter trasaction name: ");
        transName = keyboard.next();
        
        System.out.println("Enter transaction amount: ");
        transAmount = keyboard.nextDouble();
        
        System.out.println("Enter transaction cartegory: ");
        transCart = keyboard.next();
    
    }
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idTransaction", unique=true, nullable=false)
    public Integer getIdTransaction() {
        return this.idTransaction;
    }
    
    public void setIdTransaction(Integer idTransaction) {
        this.idTransaction = idTransaction;
    }

    
    @Column(name="transName", nullable=false, length=45)
    public String getTransName() {
        return this.transName;
    }
    
    public void setTransName(String transName) {
        this.transName = transName;
    }

    
    @Column(name="transAmount", nullable=false, precision=22, scale=0)
    public double getTransAmount() {
        return this.transAmount;
    }
    
    public void setTransAmount(double transAmount) {
        this.transAmount = transAmount;
    }

    
    @Column(name="transDate", nullable=false, length=45)
    public String getTransDate() {
        return this.transDate;
    }
    
    public void setTransDate(String transDate) {
        this.transDate = transDate;
    }

    
    @Column(name="transCart", length=45)
    public String getTransCart() {
        return this.transCart;
    }
    
    public void setTransCart(String transCart) {
        this.transCart = transCart;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="smarttransaction")
    public Set<Account> getAccounts() {
        return this.accounts;
    }
    
    public void setAccounts(Set<Account> accounts) {
        this.accounts = accounts;
    }




}


