package smart.budget.application;
// Generated 06 Jun 2019 12:58:24 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Wallet generated by hbm2java
 */
@Entity
@Table(name="wallet"
    ,catalog="smart_budget_data_model"
)
public class Wallet  implements java.io.Serializable {


     private Integer idwallet;
     private int rands;
     private int cents;
     private Set<Account> accounts = new HashSet<Account>(0);

    public Wallet() {
    }

	
    public Wallet(int rands, int cents) {
        this.rands = rands;
        this.cents = cents;
    }
    public Wallet(int rands, int cents, Set<Account> accounts) {
       this.rands = rands;
       this.cents = cents;
       this.accounts = accounts;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idwallet", unique=true, nullable=false)
    public Integer getIdwallet() {
        return this.idwallet;
    }
    
    public void setIdwallet(Integer idwallet) {
        this.idwallet = idwallet;
    }

    
    @Column(name="rands", nullable=false)
    public int getRands() {
        return this.rands;
    }
    
    public void setRands(int rands) {
        this.rands = rands;
    }

    
    @Column(name="cents", nullable=false)
    public int getCents() {
        return this.cents;
    }
    
    public void setCents(int cents) {
        this.cents = cents;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="wallet")
    public Set<Account> getAccounts() {
        return this.accounts;
    }
    
    public void setAccounts(Set<Account> accounts) {
        this.accounts = accounts;
    }




}


